---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        language: system

  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
      - id: blacken-docs
        language: system

  - repo: https://github.com/asottile/reorder_python_imports
    rev: master
    hooks:
      - id: reorder-python-imports
        args:
          - --application-directories=keyosk
        language: system
        exclude: "tests/"
