[tool.poetry]
name = "keyosk"
version = "0.1.0"
description = "REST API for issuing and managing JSON web tokens"
authors = ["Ethan Paul <e@enp.one>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
